import {requireAdminSession,destroyAdminSession} from "./auth.js";import {getDB,saveDB} from "./jsonbin.js";import {uploadImage} from "./cloudinary.js";
if(!(await requireAdminSession())) throw new Error("Admin session required");
let db={products:[],categories:[]},editId=null,imageUrl="";
const $=x=>document.querySelector(x), money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
async function load(){db=await getDB();db.products??=[];db.categories??=["Website","Design","Source Code","Tools"];db.settings??={};fillCats();fillSettings();render()}
function fillSettings(){const x=db.settings||{};$("#storeDescription").value=x.storeDescription||"";$("#aboutUs").value=x.aboutUs||"";$("#whatsapp").value=x.whatsapp||"";$("#whatsappLabel").value=x.whatsappLabel||"";$("#instagram").value=x.instagram||"";$("#telegram").value=x.telegram||"";$("#tiktok").value=x.tiktok||"";$("#youtube").value=x.youtube||""}
function fillCats(){$("#category").innerHTML=db.categories.map(x=>`<option>${x}</option>`).join("");$("#categoryList").innerHTML=db.categories.map(x=>`<div style="padding:6px 0;border-bottom:1px solid #222">${x}</div>`).join("")}
function render(){window.dispatchEvent(new CustomEvent("deps:stats",{detail:{products:db.products.length,categories:db.categories.length,stock:db.products.reduce((a,p)=>a+(Number(p.stock)||0),0)}}));$("#table").innerHTML=`<table class="table"><thead><tr><th>Gambar</th><th>Produk</th><th>Kategori</th><th>Harga</th><th>Stok</th><th>Aksi</th></tr></thead><tbody>${db.products.map(p=>`<tr><td>${p.image?`<img class="thumbsm" src="${p.image}">`:"—"}</td><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="btn" onclick="editProduct('${p.id}')">Edit</button> <button class="btn danger" onclick="deleteProduct('${p.id}')">Hapus</button></td></tr>`).join("")||`<tr><td colspan="6">Belum ada produk.</td></tr>`}</tbody></table>`}
window.editProduct=id=>{const p=db.products.find(x=>x.id===id);if(!p)return;editId=id;imageUrl=p.image||"";$("#name").value=p.name;$("#category").value=p.category;$("#price").value=p.price;$("#stock").value=p.stock;$("#description").value=p.description||"";$("#uploadStatus").textContent=p.image?"Gambar tersimpan.": "Belum ada gambar."}
window.deleteProduct=async id=>{if(!confirm("Hapus produk ini?"))return;db.products=db.products.filter(p=>p.id!==id);await saveDB(db);await load()}
$("#image").onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024){alert("Maksimal 8MB");return}try{$("#uploadStatus").textContent="Mengupload ke Cloudinary...";const url=await uploadImage(f,p=>$("#bar").style.width=p+"%");imageUrl=url;$("#uploadStatus").textContent="Upload berhasil. URL Cloudinary siap disimpan.";$("#bar").style.width="100%"}catch(err){$("#uploadStatus").textContent=err.message}}
$("#save").onclick=async()=>{const name=$("#name").value.trim();if(!name)return alert("Nama produk wajib diisi");const item={id:editId||("DEP-"+Date.now()),name,category:$("#category").value,price:Number($("#price").value)||0,stock:Number($("#stock").value)||0,description:$("#description").value.trim(),image:imageUrl};if(editId){const i=db.products.findIndex(p=>p.id===editId);db.products[i]=item}else db.products.unshift(item);try{await saveDB(db);alert("Produk tersimpan ke JSONBin");reset();await load()}catch(e){alert(e.message)}}
function reset(){editId=null;imageUrl="";$("#name").value="";$("#price").value="";$("#stock").value="";$("#description").value="";$("#image").value="";$("#bar").style.width="0";$("#uploadStatus").textContent="Belum ada upload."}
$("#cancel").onclick=reset;$("#logout").onclick=async()=>{await destroyAdminSession();location.replace("login.html")};
$("#addCategory").onclick=async()=>{const x=$("#newCategory").value.trim();if(!x)return;if(!db.categories.includes(x)){db.categories.push(x);await saveDB(db);$("#newCategory").value="";fillCats()}};
$("#tabCategories").onclick=()=>{$("#productsSection").hidden=true;$("#categoriesSection").hidden=false;$("#settingsSection").hidden=true;$("#tabCategories").classList.add("active");$("#tabProducts").classList.remove("active");$("#tabSettings").classList.remove("active")};$("#tabSettings").onclick=()=>{$("#productsSection").hidden=true;$("#categoriesSection").hidden=true;$("#settingsSection").hidden=false;$("#tabSettings").classList.add("active");$("#tabProducts").classList.remove("active");$("#tabCategories").classList.remove("active")};
$("#tabProducts").onclick=()=>{$("#productsSection").hidden=false;$("#categoriesSection").hidden=true;$("#settingsSection").hidden=true;$("#tabProducts").classList.add("active");$("#tabCategories").classList.remove("active");$("#tabSettings").classList.remove("active")};
$("#saveSettings").onclick=async()=>{db.settings={storeDescription:$("#storeDescription").value.trim(),aboutUs:$("#aboutUs").value.trim(),whatsapp:$("#whatsapp").value.trim().replace(/\D/g,""),whatsappLabel:$("#whatsappLabel").value.trim(),instagram:$("#instagram").value.trim(),telegram:$("#telegram").value.trim(),tiktok:$("#tiktok").value.trim(),youtube:$("#youtube").value.trim()};try{await saveDB(db);alert("Pengaturan footer tersimpan ke JSONBin")}catch(e){alert(e.message)}};
load().catch(e=>alert(e.message));